services:
  - type: web
    name: talkers-intranet-chat
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATA_DIR
        value: /data
      - key: INDEX_FOLDER
        value: /data/kb
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://SEU-SERVICO.onrender.com
      - key: AUTO_SEED_ON_BOOT
        value: "false"
      - key: AUTO_INDEX_ON_BOOT
        value: "false"
